Traceback (most recent call last):
  File "rur_start.py", line 169, in OnClose
  File "rur_start.py", line 351, in SaveProgramFile
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 41: ordinal not in range(128)
Traceback (most recent call last):
  File "rur_start.py", line 351, in SaveProgramFile
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128)
Traceback (most recent call last):
  File "rur_start.py", line 169, in OnClose
  File "rur_start.py", line 351, in SaveProgramFile
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128)
Traceback (most recent call last):
  File "rur_start.py", line 169, in OnClose
  File "rur_start.py", line 351, in SaveProgramFile
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128)
Traceback (most recent call last):
  File "rur_start.py", line 351, in SaveProgramFile
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128)
Traceback (most recent call last):
  File "rur_start.py", line 169, in OnClose
  File "rur_start.py", line 351, in SaveProgramFile
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128)
